--DDL
CREATE DATABASE SENAI_HROADS_TARDE;
GO

USE SENAI_HROADS_TARDE;
GO

CREATE TABLE CLASSE (
	idClasse TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeClasse VARCHAR(25) NOT NULL
);
GO

CREATE TABLE TIPOHABILIDADE (
	idTipoHabilidade TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeTipoHabilidade VARCHAR(20) NOT NULL
);
GO

CREATE TABLE HABILIDADE (
	idHabilidade TINYINT PRIMARY KEY IDENTITY(1,1),
	idTipoHabilidade TINYINT FOREIGN KEY REFERENCES TIPOHABILIDADE (idTipoHabilidade),
	nomeHabilidade VARCHAR(35) NOT NULL
);
GO

CREATE TABLE CLASSEHABILIDADE (
	idClasseHabilidade SMALLINT PRIMARY KEY IDENTITY(1,1),
	idHabilidade TINYINT FOREIGN KEY REFERENCES HABILIDADE(idHabilidade),
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse)
);
GO

CREATE TABLE PERSONAGEM (
	idPersonagem SMALLINT PRIMARY KEY IDENTITY(1,1),
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse),
	nomePersonagem VARCHAR (60) NOT NULL,
	capMaxVida VARCHAR (100) NOT NULL,
	capMaxMana VARCHAR (100) NOT NULL,
	dataAtualizacao SMALLDATETIME NOT NULL,
	DataCriacao SMALLDATETIME NOT NULL 
);
GO